### ISSUE TITLE
Some numeric values in results have an extra blank (or something)

### ISSUE THREAD

**Issue by SJLennon** [IBM/ibmi-db2util#17] opened 2021-09-01 15:40 UTC
Start QP2TERM and run this command:
`db2util -o json "select cusnum,cdtdue from QIWS/QCUSTCDT "`
The first two records are different in how they present the CDTDUE value. The second one has an extra character.
```
 {"records":[                      
 {"CUSNUM":938472,"CDTDUE":0.00},  
 {"CUSNUM":839283,"CDTDUE":0.00 }, 
```

There are other variances as well. Here's a screen shot:
![image](https://user-images.githubusercontent.com/67484051/131701240-030d0c24-8984-4a01-85fb-1f4ab0e532fb.png)

**Comment by markdirish** [comment] 2021-09-01 19:24
I have recreated this issue, but only in a 5250 emulator using QP2TERM. When I use it with an ssh session in my GNOME Terminal with bash, I see none of these extra spaces. Will continue to poke around to see what could be the underlying issue.

**Comment by SJLennon** [comment] 2021-09-01 21:05
@markdirish   I ran into this in the  vscode-ibmi extension to VS Code. Liam said he could duplicated it.

I now see that issue #14 may be similar.

This is the debug log that vscode-ibmi put out. There are instances of \u0000.

/home/LENNONS: DB2UTIL_JSON_CONTAINER=array /QOpenSys/pkgs/bin/db2util -o json "select cusnum,cdtdue from QIWS/QCUSTCDT"
{
    "code": null,
    "signal": null,
    "stdout": "[\n{\"CUSNUM\":938472,\"CDTDUE\":0.00},\n{\"CUSNUM\":839283,\"CDTDUE\":0.00\u0000},\n{\"CUSNUM\":392859,\"CDTDUE\":0.00\u0000},\n{\"CUSNUM\":938485,\"CDTDUE\":33.50\u0000},\n{\"CUSNUM\":397267,\"CDTDUE\":0.00},\n{\"CUSNUM\":389572,\"CDTDUE\":1.50\u0000},\n{\"CUSNUM\":846283,\"CDTDUE\":0.00},\n{\"CUSNUM\":475938,\"CDTDUE\":100.00\u0000},\n{\"CUSNUM\":693829,\"CDTDUE\":0.00},\n{\"CUSNUM\":593029,\"CDTDUE\":0.00\u0000},\n{\"CUSNUM\":192837,\"CDTDUE\":0.50\u0000},\n{\"CUSNUM\":583990,\"CDTDUE\":0.00\u0000}\n]",
    "stderr": ""
}

**Comment by kadler** [comment] 2021-09-08 20:07
Yeah, I suspect this is a duplicate of #14 and there's a PR for that already. Can you test with the changes in that branch?

Easiest way would be something like this (from a PASE shell):
```
wget https://github.com/IBM/ibmi-db2util/archive/refs/heads/save-bound-pointer.tar.gz
gzip -d save-bound-pointer.tar.gz
tar -xf save-bound-pointer.tar
cd ibmi-db2util-save-bound-pointer/
make
```

Assuming you have the build dependencies listed [here](https://github.com/IBM/ibmi-db2util#build-dependencies) this should build pretty painlessly.

**Comment by kadler** [comment] 2021-09-10 18:13
We've pushed out 1.0.12 via yum. I believe this issue is fixed in that release. Please re-open if not the case.

**Closed by kadler** 2021-09-10 18:13 UTC
